#include <Arduino.h>
#include <WiFi.h>
#include <WebServer.h>
#include <ArduinoJson.h>
#include <Update.h>
#include <esp_app_format.h>
#include <time.h>
#include "../config.h"
#include "settings.h"
#include "mvg_api.h"
#include "portal.h"

#define PORTAL_TASK_STACK 12288
#define PORTAL_HELP_URL "https://github.com/Fluddel94/MVG_Abfahrtsdisplay_E290"
// Absichtlich kompatibel zur Original-Firmware, damit OTA-Wechsel moeglich bleibt.
static const char FIRMWARE_MARKER[] = "MVG_Abfahrtsdisplay_E290/firmware";

static const char PAGE_HEAD[] = R"HTML(<!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>VBB Abfahrtsdisplay</title><style>
body{font-family:system-ui,sans-serif;margin:0;background:#f2f2f2;color:#111}main{max-width:720px;margin:auto;padding:12px}h1{font-size:1.45em;margin:8px 0}.hint{color:#555;font-size:.9em}section{background:#fff;border-radius:9px;padding:13px;margin:12px 0}h2{font-size:1.1em;margin:0 0 8px}h3{font-size:1em;margin:5px 0}.station{border:1px solid #ccc;border-radius:8px;padding:10px;margin:10px 0}.row{display:flex;gap:8px;flex-wrap:wrap}.row>*{flex:1}input[type=text],select{width:100%;box-sizing:border-box;padding:8px;font-size:1em}label{display:block;margin:7px 0 3px}.cb{display:flex;align-items:center;gap:8px;margin:6px 0}.cb label{margin:0}.cb input{width:20px;height:20px}button{padding:9px 13px;border:1px solid #888;border-radius:6px;background:#eee;font-size:1em}.main{width:100%;background:#075da8;color:white;border-color:#075da8;padding:12px}.danger{color:#a00;background:#fff;border-color:#a00}.hits button{display:block;width:100%;text-align:left;margin:5px 0}.dirs{margin-top:7px}.dir{display:grid;grid-template-columns:minmax(130px,1fr) 75px 75px 75px;gap:5px;align-items:center;border-top:1px solid #eee;padding:5px 0}.dir small{color:#666}.pill{font-size:.8em;background:#eee;border-radius:10px;padding:2px 6px}.hidden{display:none}progress{width:100%}</style></head><body><main><h1>VBB Abfahrtsdisplay</h1><p class="hint">Berlin/Brandenburg · bis zu 4 Bahnhöfe/Haltestellen · Heltec Vision Master E290</p>
<form method="post" action="/speichern" id="form" onsubmit="return prepareSave()">
<section><h2>Bahnhöfe / Haltestellen</h2><div id="stationList"></div></section>
<section><h2>Anzeige</h2><label>Modus</label><select id="dirView" name="dirView"><option value="0">Alle Richtungen gemischt (2 Seiten je Bahnhof)</option><option value="1">Getrennt nach Richtung A / B</option></select><p class="hint">BOOT kurz läuft durch alle Ansichten. BOOT 2 s springt direkt zum nächsten belegten Bahnhof.</p></section>
<section><h2>Verkehrsmittel</h2><div class="cb"><input type="checkbox" id="sbahn" name="sbahn"><label for="sbahn">S-Bahn</label></div><div class="cb"><input type="checkbox" id="ubahn" name="ubahn"><label for="ubahn">U-Bahn</label></div><div class="cb"><input type="checkbox" id="tram" name="tram"><label for="tram">Tram</label></div><div class="cb"><input type="checkbox" id="bus" name="bus"><label for="bus">Bus</label></div><div class="cb"><input type="checkbox" id="bahn" name="bahn"><label for="bahn">Regional- und Fernverkehr</label></div></section>
<section><h2>WLAN-QR-Code</h2><div class="cb"><input type="checkbox" id="qrOn" name="qrOn"><label for="qrOn">Kurzer Druck auf die mittlere Taste zeigt WLAN-QR</label></div><label>Überschrift</label><input id="qrTitle" name="qrTitle" type="text" maxlength="40"><label>WLAN-Name</label><input id="qrSsid" name="qrSsid" type="text" maxlength="32"><label>Passwort</label><input id="qrPass" name="qrPass" type="text" maxlength="63" autocomplete="off"><p class="hint">Leer lassen = vorhandenes QR-Passwort unverändert.</p></section>
<button class="main" type="submit">Speichern</button></form>
<section><h2>Gerät</h2><p>WLAN: <b id="wifi"></b> · Signal <span id="rssi"></span> dBm<br>Firmware <span id="version"></span> · IP <span id="ip"></span></p><p id="closes" class="hint"></p><p><b>Firmware aktualisieren</b></p><input type="file" id="fw" accept=".bin"><p><button type="button" id="fwBtn" onclick="uploadFw()">Hochladen</button></p><progress id="fwBar" max="100" value="0" style="display:none"></progress><p id="fwMsg"></p><form method="post" action="/werkseinstellungen" onsubmit="return confirm('Alle Einstellungen inklusive WLAN löschen?')"><button class="danger">Werkseinstellungen</button></form></section>
)HTML";

static const char PAGE_SCRIPT[] = R"HTML(<script>
const $=x=>document.getElementById(x),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let C=S.stations.map(s=>({id:s.id||'',name:s.name||'',la:s.la||'Richtung A',lb:s.lb||'Richtung B',defA:s.defA!==false,a:parseArr(s.da),b:parseArr(s.db),targets:[]}));
function parseArr(x){try{let a=JSON.parse(x||'[]');return Array.isArray(a)?a:[]}catch(e){return []}}
function stationHtml(i){let c=C[i];return `<div class=station><h3>Bahnhof ${i+1} <span class=pill id=sel${i}>${c.id?'belegt':'leer'}</span></h3><label>Haltestelle suchen</label><div class=row><input id=q${i} type=text placeholder="z.B. Alexanderplatz"><button type=button onclick="searchStop(${i})">Suchen</button></div><div class=hits id=hits${i}></div><label>VBB Stations-ID</label><input type=text id=st${i} name=st${i} value="${esc(c.id)}" placeholder="z.B. 900100003"><input type=hidden id=sn${i} name=sn${i} value="${esc(c.name)}"><p class=hint id=name${i}>${c.name?`Gewählt: ${esc(c.name)}`:'Noch nicht belegt'}</p><div class=row><div><label>Name Richtung A</label><input type=text id=la${i} name=la${i} value="${esc(c.la)}" maxlength=40></div><div><label>Name Richtung B</label><input type=text id=lb${i} name=lb${i} value="${esc(c.lb)}" maxlength=40></div></div><label>Standardrichtung</label><select id=df${i} name=df${i}><option value=A ${c.defA?'selected':''}>A</option><option value=B ${!c.defA?'selected':''}>B</option></select><p><button type=button onclick="loadDirs(${i})">Ziele / Richtungen laden</button> <button type=button onclick="clearStation(${i})">Slot leeren</button></p><div class=dirs id=dirs${i}></div><input type=hidden id=da${i} name=da${i}><input type=hidden id=db${i} name=db${i}></div>`}
function render(){ $('stationList').innerHTML=[0,1,2,3].map(stationHtml).join(''); }
async function searchStop(i){let q=$(`q${i}`).value.trim();if(q.length<2)return;$(`hits${i}`).textContent='Suche ...';try{let r=await fetch('/suche?q='+encodeURIComponent(q)),a=await r.json();$(`hits${i}`).innerHTML=a.map(s=>`<button type=button data-id="${esc(s.id)}"><b>${esc(s.n)}</b><br><small>${esc(s.t||'')} · ID ${esc(s.id)}</small></button>`).join('')||'Keine Haltestelle gefunden.';[...$(`hits${i}`).querySelectorAll('button')].forEach((b,k)=>b.onclick=()=>choose(i,a[k]));}catch(e){$(`hits${i}`).textContent='Suche fehlgeschlagen.'}}
function choose(i,s){C[i].id=s.id;C[i].name=s.n;$(`st${i}`).value=s.id;$(`sn${i}`).value=s.n;$(`name${i}`).textContent='Gewählt: '+s.n;$(`sel${i}`).textContent='belegt';$(`hits${i}`).innerHTML='';C[i].a=[];C[i].b=[];loadDirs(i)}
function clearStation(i){C[i]={id:'',name:'',la:'Richtung A',lb:'Richtung B',defA:true,a:[],b:[],targets:[]};$(`st${i}`).value='';$(`sn${i}`).value='';$(`la${i}`).value='Richtung A';$(`lb${i}`).value='Richtung B';$(`df${i}`).value='A';$(`name${i}`).textContent='Noch nicht belegt';$(`dirs${i}`).innerHTML='';$(`sel${i}`).textContent='leer'}
async function loadDirs(i){let id=$(`st${i}`).value.trim();if(!id){alert('Erst eine Haltestelle wählen.');return}$(`dirs${i}`).textContent='Lade Ziele ...';try{let r=await fetch('/richtungen?id='+encodeURIComponent(id)),a=await r.json();C[i].targets=a;drawDirs(i)}catch(e){$(`dirs${i}`).textContent='Abruf fehlgeschlagen.'}}
function group(i,z){if(C[i].a.includes(z))return'A';if(C[i].b.includes(z))return'B';return''}
function setGroup(i,z,g){C[i].a=C[i].a.filter(x=>x!==z);C[i].b=C[i].b.filter(x=>x!==z);if(g==='A')C[i].a.push(z);if(g==='B')C[i].b.push(z)}
function drawDirs(i){let a=C[i].targets;if(!a.length){$(`dirs${i}`).textContent='Keine Ziele gefunden.';return}$(`dirs${i}`).innerHTML=a.map((d,k)=>{let g=group(i,d.z);return `<div class=dir><div><b>${esc(d.z)}</b><br><small>${esc(d.l||'')}</small></div>${['A','B',''].map(x=>`<label><input type=radio name=g${i}_${k} data-k=\"${k}\" data-g=\"${x}\" ${g===x?'checked':''}>${x||'ignor.'}</label>`).join('')}</div>`}).join('');[...$(`dirs${i}`).querySelectorAll('input[type=radio]')].forEach(r=>r.onchange=()=>{let d=a[Number(r.dataset.k)];setGroup(i,d.z,r.dataset.g)})}
function prepareSave(){let occupied=false;for(let i=0;i<4;i++){C[i].id=$(`st${i}`).value.trim();C[i].name=$(`sn${i}`).value.trim();if(C[i].id)occupied=true;$(`da${i}`).value=JSON.stringify(C[i].a);$(`db${i}`).value=JSON.stringify(C[i].b)}if(!occupied){alert('Mindestens einen Bahnhof wählen.');return false}if(!['sbahn','ubahn','tram','bus','bahn'].some(x=>$(x).checked)){alert('Mindestens ein Verkehrsmittel wählen.');return false}return true}
function uploadFw(){const f=$('fw').files[0];if(!f){alert('Bitte .bin wählen.');return}if(f.size>S.fwMax){alert('Datei zu groß.');return}if(!confirm('Firmware '+f.name+' aufspielen?'))return;let fd=new FormData();fd.append('firmware',f,f.name);let x=new XMLHttpRequest();x.open('POST','/update');x.upload.onprogress=e=>{if(e.lengthComputable)$('fwBar').value=e.loaded*100/e.total};x.onload=()=>{$('fwMsg').textContent=x.status==200?'Erfolgreich – Neustart läuft.':'Fehler: '+x.responseText};x.onerror=()=>{$('fwMsg').textContent='Verbindung abgebrochen.'};$('fwBar').style.display='';x.send(fd)}
render();$('dirView').value=S.dirView?'1':'0';['sbahn','ubahn','tram','bus','bahn','qrOn'].forEach(x=>$(x).checked=!!S[x]);$('qrTitle').value=S.qrTitle||'';$('qrSsid').value=S.qrSsid||'';if(S.qrPassSet)$('qrPass').placeholder='unverändert';$('wifi').textContent=S.wifi;$('rssi').textContent=S.rssi;$('version').textContent=S.version;$('ip').textContent=S.ip;$('closes').textContent=S.closes?'Portal offen bis '+S.closes+' Uhr':'';
</script></body></html>)HTML";

static WebServer* server=nullptr;static volatile bool running=false;static volatile unsigned long openStart=0;static String firmwareVersionCopy;
static volatile bool pendingSave=false,pendingReset=false,updateRunning=false,pendingRestart=false;static DeviceSettings pendingSettings;static String updateError;static bool updateHeaderChecked=false,markerFound=false;static size_t markerPos=0;

static String formArg(const char* n,unsigned int maxLen){String v=server->arg(n);v.trim();if(v.length()>maxLen)v=v.substring(0,maxLen);return v;}
static bool validStationId(const String&id){if(!id.length())return true;if(id.length()>64)return false;for(unsigned int i=0;i<id.length();i++){char c=id[i];if(!isalnum((unsigned char)c)&&c!=':'&&c!='_'&&c!='-')return false;}return true;}
static bool targetArrayArg(const String&name,String&out){out=server->arg(name);if(out.length()>900)return false;JsonDocument d;if(deserializeJson(d,out))return false;return d.is<JsonArray>();}
static void sendMessage(int code,const char*msg){String p=F("<!doctype html><meta charset=utf-8><meta name=viewport content='width=device-width'><body style='font-family:system-ui;max-width:600px;margin:auto;padding:20px'><h1>VBB Abfahrtsdisplay</h1><p>");p+=msg;p+=F("</p><p><a href='/'>Zurück</a></p>");server->send(code,"text/html; charset=utf-8",p);}

static void handleRoot(){JsonDocument d;{SettingsLock lock;d["dirView"]=appSettings.directionView;JsonArray ss=d["stations"].to<JsonArray>();for(int i=0;i<MAX_STATIONS;i++){JsonObject x=ss.add<JsonObject>();auto&s=appSettings.stations[i];x["id"]=s.id;x["name"]=s.name;x["da"]=s.dirAJson;x["db"]=s.dirBJson;x["la"]=s.labelA;x["lb"]=s.labelB;x["defA"]=s.defaultA;}d["sbahn"]=appSettings.showSbahn;d["ubahn"]=appSettings.showUbahn;d["tram"]=appSettings.showTram;d["bus"]=appSettings.showBus;d["bahn"]=appSettings.showBahn;d["qrOn"]=appSettings.wifiQr;d["qrTitle"]=appSettings.qrTitle;d["qrSsid"]=appSettings.qrSsid;d["qrPassSet"]=appSettings.qrPassword.length()>0;d["wifi"]=appSettings.wifiSsid;}d["rssi"]=WiFi.RSSI();d["version"]=firmwareVersionCopy;d["ip"]=WiFi.localIP().toString();d["closes"]=portalClosingTime();d["fwMax"]=ESP.getFreeSketchSpace();String j;serializeJson(d,j);j.replace("<","\\u003c");String p;p.reserve(sizeof(PAGE_HEAD)+sizeof(PAGE_SCRIPT)+j.length()+40);p+=PAGE_HEAD;p+="<script>const S="+j+";</script>\n";p+=PAGE_SCRIPT;server->send(200,"text/html; charset=utf-8",p);}

static void handleSave(){if(pendingSave){sendMessage(503,"Bitte kurz warten.");return;}DeviceSettings s;{SettingsLock lock;s=appSettings;}bool occupied=false;for(int i=0;i<MAX_STATIONS;i++){String n="st"+String(i);String id=formArg(n.c_str(),64);if(!validStationId(id)){sendMessage(400,"Ungültige Stations-ID.");return;}s.stations[i].id=id;n="sn"+String(i);s.stations[i].name=formArg(n.c_str(),80);n="da"+String(i);if(!targetArrayArg(n,s.stations[i].dirAJson)){sendMessage(400,"Richtung A enthält zu viele oder ungültige Ziele.");return;}n="db"+String(i);if(!targetArrayArg(n,s.stations[i].dirBJson)){sendMessage(400,"Richtung B enthält zu viele oder ungültige Ziele.");return;}n="la"+String(i);s.stations[i].labelA=formArg(n.c_str(),40);n="lb"+String(i);s.stations[i].labelB=formArg(n.c_str(),40);n="df"+String(i);s.stations[i].defaultA=server->arg(n)=="A";if(id.length())occupied=true;}if(!occupied){sendMessage(400,"Mindestens einen Bahnhof wählen.");return;}s.directionView=server->arg("dirView")=="1";s.showSbahn=server->hasArg("sbahn");s.showUbahn=server->hasArg("ubahn");s.showTram=server->hasArg("tram");s.showBus=server->hasArg("bus");s.showBahn=server->hasArg("bahn");if(!(s.showSbahn||s.showUbahn||s.showTram||s.showBus||s.showBahn)){sendMessage(400,"Mindestens ein Verkehrsmittel wählen.");return;}s.wifiQr=server->hasArg("qrOn");s.qrTitle=formArg("qrTitle",40);s.qrSsid=formArg("qrSsid",32);String qrp=server->arg("qrPass");if(qrp.length()>63)qrp=qrp.substring(0,63);if(qrp.length())s.qrPassword=qrp;pendingSettings=s;pendingSave=true;sendMessage(200,"Gespeichert. Die Anzeige wird neu aufgebaut.");}
static void handleSearch(){String q=formArg("q",50),j;if(q.length()<2)j="[]";else if(!searchStations(q,j)){server->send(502,"application/json","{\"error\":\"VBB nicht erreichbar\"}");return;}server->send(200,"application/json; charset=utf-8",j);}
static void handleDirections(){String id=formArg("id",64),j;if(!validStationId(id)||!id.length()||!listDirections(id.c_str(),j)){server->send(502,"application/json","{\"error\":\"Abruf fehlgeschlagen\"}");return;}server->send(200,"application/json; charset=utf-8",j);}
static void handleFactoryReset(){pendingReset=true;sendMessage(200,"Werkseinstellungen werden gelöscht; Neustart folgt.");}

static void scanMarker(const uint8_t*data,size_t len){size_t ml=sizeof(FIRMWARE_MARKER)-1;for(size_t i=0;i<len&&!markerFound;i++){char c=(char)data[i];if(c==FIRMWARE_MARKER[markerPos]){if(++markerPos==ml)markerFound=true;}else markerPos=(c==FIRMWARE_MARKER[0])?1:0;}}
static void failUpdate(const char*m){if(!updateError.length())updateError=m;Update.abort();}
static bool checkHeader(const uint8_t*d,size_t n){if(n<16||d[0]!=0xE9)return false;uint16_t chip=d[12]|(d[13]<<8);return chip==ESP_CHIP_ID_ESP32S3;}
static void handleUpdateUpload(){HTTPUpload&u=server->upload();if(u.status==UPLOAD_FILE_START){openStart=millis();updateError="";updateHeaderChecked=false;markerFound=false;markerPos=0;updateRunning=true;if(!Update.begin(UPDATE_SIZE_UNKNOWN,U_FLASH))failUpdate("Update konnte nicht gestartet werden.");}else if(u.status==UPLOAD_FILE_WRITE){if(updateError.length())return;openStart=millis();if(!updateHeaderChecked){updateHeaderChecked=true;if(!checkHeader(u.buf,u.currentSize)){failUpdate("Keine ESP32-S3-Firmware.");return;}}scanMarker(u.buf,u.currentSize);if(Update.write(u.buf,u.currentSize)!=u.currentSize)failUpdate("Schreiben fehlgeschlagen.");}else if(u.status==UPLOAD_FILE_END){if(updateError.length())return;if(!markerFound)failUpdate("Keine passende Abfahrtsdisplay-Firmware.");else if(!Update.end(true))failUpdate("Datei beschädigt oder unvollständig.");}else if(u.status==UPLOAD_FILE_ABORTED){failUpdate("Upload abgebrochen.");updateRunning=false;}}
static void handleUpdateDone(){if(updateError.length()||!updateHeaderChecked){String m=updateError.length()?updateError:"Keine Datei empfangen.";updateRunning=false;server->send(400,"text/plain; charset=utf-8",m);return;}server->send(200,"text/plain","ok");pendingRestart=true;}

static void portalTask(void*){while(millis()-openStart<PORTAL_DURATION_MS){server->handleClient();vTaskDelay(pdMS_TO_TICKS(5));}server->stop();delete server;server=nullptr;running=false;vTaskDelete(nullptr);}
void portalBegin(const char*v){firmwareVersionCopy=v;}
void portalOpen(){openStart=millis();if(running)return;server=new WebServer(80);server->on("/",HTTP_GET,handleRoot);server->on("/speichern",HTTP_POST,handleSave);server->on("/werkseinstellungen",HTTP_POST,handleFactoryReset);server->on("/suche",HTTP_GET,handleSearch);server->on("/richtungen",HTTP_GET,handleDirections);server->on("/update",HTTP_POST,handleUpdateDone,handleUpdateUpload);server->onNotFound([](){server->sendHeader("Location","/");server->send(302,"text/plain","");});server->begin();running=true;xTaskCreate(portalTask,"portal",PORTAL_TASK_STACK,nullptr,1,nullptr);}
bool portalIsOpen(){return running;}String portalUrl(){return "http://"+WiFi.localIP().toString()+"/";}
String portalClosingTime(){const time_t MIN=1700000000;time_t now=time(nullptr);if(now<MIN||!running)return"";unsigned long remaining=PORTAL_DURATION_MS-(millis()-openStart);time_t c=now+remaining/1000;struct tm t;localtime_r(&c,&t);char b[6];snprintf(b,sizeof(b),"%02d:%02d",t.tm_hour,t.tm_min);return String(b);}
bool portalUpdateRunning(){return updateRunning;}
bool portalLoop(){if(pendingRestart){delay(700);ESP.restart();}if(pendingReset){settingsFactoryReset();delay(700);ESP.restart();}if(!pendingSave)return false;{SettingsLock lock;appSettings=pendingSettings;}settingsSave();settingsPrint();pendingSave=false;return true;}
